/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "auth.h"

bool_t
xdr_Auth_Response (XDR *xdrs, Auth_Response *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->accessToken, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->refreshToken, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->expiry))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Auth_Request (XDR *xdrs, Auth_Request *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->requestToken, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->shouldRefresh))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Action_Request (XDR *xdrs, Action_Request *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->accessToken, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->resource, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->action, ~0))
		 return FALSE;
	return TRUE;
}
